### ISSUE TITLE
Fix ImportError in /api/pipeline/retrieve (broken since initial commit)

### ISSUE THREAD

**Issue by GitHubPJ69** [MODSetter/SurfSense#1302]
POST /api/pipeline/retrieve returns 500 with `ImportError: cannot import name 'retrieve_knowledge_base_documents' from app.agents.new_chat.tools.knowledge_base`.

The function has never existed. Introduced in 2080195b8. Correct function is `search_knowledge_base_raw_async` (returns `list[dict]`, matching what the endpoint response expects).

Fix: update import and call site in `surfsense_backend/app/routes/pipeline_api.py` lines 94-111.

Discovered while smoke-testing the Phase 0 Oracle skill (#27, PR #28).

**Comment by GitHubPJ69** [comment]
Filed on wrong repo — this is a fork-local bug in the-original-body/tob-oracle. Reopening there.
